# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='plexiglass',
    version='0.0.1',
    description='Pure Python common utilities',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "homepage": "https://github.com/kudu/plexiglass",
        "repository": "https://github.com/kudu/plexiglass"
    },
    author='Eric Lee',
    author_email='elee@kududyn.com',
    classifiers=[
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8', 'Private :: Do Not Upload'
    ],
    packages=['plexiglass'],
    package_dir={"": "."},
    package_data={},
    install_requires=['structlog>=18.2.0'],
    extras_require={
        "dev": [
            "colorama", "pytest", "pytest-black", "pytest-cov", "pytest-flake8"
        ],
        "synapse": ["synapse<0.2.0"]
    },
)
